---
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-toml
    - id: check-added-large-files
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.14.8
  hooks:
    - id: ruff-check
      args: [--fix]
    - id: ruff-format
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.20.1
  hooks:
    - id: mypy
      args: [--strict, --ignore-missing-imports, --scripts-are-modules]
      additional_dependencies: ["pyjwt[crypto]", "myconso==0.0.13", "homeassistant>=2026.3.0"]
      exclude: "^(tests/|examples/)$"
      files: custom_components/
