[project]
name = "myconso_ha"
version = "0.0.7"
description = "Proxiserver myconso in ha"
readme = "README.md"
requires-python = ">=3.14.2"
authors = [
    {name = "Rémi Jouannet", email = "remijouannet@gmail.com"},
]
dependencies = [
    "homeassistant>=2026.3.0",
]

[dependency-groups]
dev = [
    "pre-commit",
    "ruff",
    "mypy",
    "pytest>=9.0.0",
    "pytest-asyncio",
    "homeassistant",
    "pytest-homeassistant-custom-component",
    "myconso==0.0.15",
]

[tool.uv]
required-version = ">=0.8.0"

[tool.pytest.ini_options]
asyncio_mode = "auto"

[tool.mypy]
plugins = ["pydantic.mypy"]
exclude = "tests/"
files = "custom_components/"
strict = true

[tool.ruff]
line-length = 88
include = ["custom_components/myconso_ha/*.py", "tests/*.py"]

[tool.ruff.lint]
select = [
    # flake8-async
    "ASYNC",
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # flake8-bugbear
    "B",
    # flake8-simplify
    "SIM",
    # isort
    "I",
    # ruff
    "RUF",
    # flake8-quotes
    "Q",
    # pylint
    "PL",
]
